"""
Manageable finding records — turns description/remediation text into a work queue.

Findings are generated by the rule engine (deterministic ID: finding-{asset_id}-{rule_key}),
kept in a persistent store (findings.json). Every scan:
  - new finding → create record (status Open, first_seen=now)
  - existing finding → refresh last_seen, refresh rule content
  - seen again while Resolved → Reopened (criterion 4)
  - open finding no longer seen → auto-Resolved
Manual fields (owner, responsible_team, due_date, status, resolution_note,
ticket_reference) are NEVER overwritten by a scan.
"""
from datetime import datetime, timezone

import storage
from config import FINDING_STATUSES as STATUSES
from scoring import _scope_weight

OPEN_STATUSES = {"Open", "Assigned", "In Progress", "Pending Review", "Reopened"}
CLOSED_STATUSES = {"Resolved", "Accepted", "False Positive"}


def _maxw_delegated(app):
    return max((_scope_weight(s) for s in app.get("scopes", [])), default=0)


def _maxw_app(app):
    return max((_scope_weight((p.get("permission") or "").lower())
                for p in app.get("application_permissions", [])), default=0)


def _review_overdue(app, now):
    d = (app.get("lifecycle") or {}).get("next_review_date")
    if not d:
        return False
    try:
        dt = datetime.fromisoformat(d.replace("Z", "+00:00"))
    except (ValueError, AttributeError):
        return False
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt < now


# Rule = (key, title, description, category, severity, priority, action, impact, applies)
RULES = [
    ("owner-missing", "No business owner assigned",
     "No business owner has been assigned to this application — no accountability.",
     "Governance", "Medium", "P2", "Assign a business owner.",
     "Unowned AI application; unclear who is responsible during an incident.",
     lambda a, now: not (a.get("ownership") or {}).get("business_owner")
     and not a.get("first_party_microsoft")),

    ("admin-consent-sensitive", "Sensitive permission on an admin-consented app",
     "Admin consent has been granted for the entire organization and a sensitive data permission is present.",
     "Permission", "High", "P1", "Review/remove the admin consent; apply least-privilege.",
     "Org-wide sensitive data access — wide blast radius.",
     lambda a, now: a.get("consent_type") == "AllPrincipals" and _maxw_delegated(a) >= 8),

    ("app-only-highpriv", "High-privilege app-only access",
     "The application has high-privilege tenant access without a user (app-only).",
     "Permission", "High", "P1", "Revoke the app-only application permissions.",
     "Unattended, 24/7 tenant-wide access.",
     lambda a, now: a.get("has_app_only_access") and _maxw_app(a) >= 8),

    ("unknown-classification", "Unclassified AI application",
     "The application was classified as Unknown AI — cannot be assumed safe.",
     "Classification", "Medium", "P2", "Review and classify into the correct category.",
     "Ungoverned, undefined AI risk.",
     lambda a, now: (a.get("classification") or {}).get("category") == "Unknown AI"),

    ("unused-high-risk", "Unused high-risk application",
     "High-risk application that hasn't been used in the last 30 days — pure attack surface.",
     "Usage", "Medium", "P2", "Remove access / delete the application if not needed.",
     "No business value but the permission risk persists.",
     lambda a, now: (a.get("usage") or {}).get("inactive_30d") and a.get("risk_score", 0) >= 50),

    ("lifecycle-review-overdue", "Lifecycle review overdue",
     "The application's scheduled review date has passed.",
     "Governance", "Low", "P3", "Complete the lifecycle review and update the date.",
     "Governance SLA breach.",
     lambda a, now: _review_overdue(a, now)),

    ("blocked-still-active", "Blocked application still in use",
     "Lifecycle is Blocked but the application was actively used in the last 30 days.",
     "Governance", "High", "P1", "Technically cut off access (remove consent / disable).",
     "Policy violation — a blocked app is being used.",
     lambda a, now: (a.get("lifecycle") or {}).get("status") == "Blocked"
     and (a.get("usage") or {}).get("active_users_30d", 0) > 0),
]


def generate(apps, now):
    """Generates current findings from the rules → {finding_id: generated_fields}."""
    out = {}
    for app in apps:
        aid = app.get("app_id") or app.get("sp_id")
        if not aid:
            continue
        for key, title, desc, cat, sev, prio, action, impact, applies in RULES:
            try:
                if not applies(app, now):
                    continue
            except Exception:
                continue
            fid = f"finding-{aid}-{key}"
            out[fid] = {
                "finding_id": fid, "rule_key": key, "title": title, "description": desc,
                "category": cat, "severity": sev, "priority": prio,
                "asset_id": aid, "asset_name": app.get("display_name") or "—",
                "business_impact": impact, "recommended_action": action,
            }
    return out


def _default(gen, now):
    d = now.date().isoformat()
    rec = dict(gen)
    rec.update({"status": "Open", "owner": "", "responsible_team": "", "due_date": None,
                "first_seen": d, "last_seen": d, "resolution_note": "",
                "ticket_reference": "", "closed_date": None, "history": []})
    return rec


def process(apps, now=None):
    """Generates findings, reconciles with the store, persists; returns the record list."""
    now = now or datetime.now(timezone.utc)
    today = now.date().isoformat()
    gen = generate(apps, now)
    store = storage.read_json("findings.json") or {}

    for fid, g in gen.items():
        rec = store.get(fid)
        if rec is None:
            store[fid] = _default(g, now)
            continue
        # Refresh scan-derived fields (don't touch manual fields)
        for k in ("title", "description", "category", "severity", "priority",
                  "asset_name", "business_impact", "recommended_action", "rule_key"):
            rec[k] = g[k]
        rec["last_seen"] = today
        if rec["status"] == "Resolved":          # a resolved finding came back → Reopened
            rec["history"].append({"timestamp": now.isoformat(), "field": "status",
                                   "from": "Resolved", "to": "Reopened"})
            rec["status"] = "Reopened"
            rec["closed_date"] = None

    # Open findings no longer seen → auto-Resolved
    for fid, rec in store.items():
        if fid not in gen and rec.get("status") in OPEN_STATUSES:
            rec["history"].append({"timestamp": now.isoformat(), "field": "status",
                                   "from": rec["status"], "to": "Resolved"})
            rec["status"] = "Resolved"
            rec["closed_date"] = today
            if not rec.get("resolution_note"):
                rec["resolution_note"] = "Automatic: finding is no longer detected."

    storage.write_json("findings.json", store)
    return list(store.values())


def set_finding(store, finding_id, patch, now=None):
    """Manual update (dashboard/config): owner, team, due date, status, etc."""
    now = now or datetime.now(timezone.utc)
    rec = store.get(finding_id)
    if rec is None:
        return None
    new_status = patch.get("status")
    if new_status in STATUSES and new_status != rec["status"]:
        rec["history"].append({"timestamp": now.isoformat(), "field": "status",
                               "from": rec["status"], "to": new_status})
        rec["status"] = new_status
        rec["closed_date"] = now.date().isoformat() if new_status in CLOSED_STATUSES else None
    for k in ("owner", "responsible_team", "due_date", "resolution_note", "ticket_reference"):
        if k in patch and patch[k] is not None:
            rec[k] = patch[k]
    return rec


def _parse_date(s):
    if not s:
        return None
    try:
        dt = datetime.fromisoformat(str(s).replace("Z", "+00:00"))
    except (ValueError, AttributeError):
        return None
    return dt.replace(tzinfo=timezone.utc) if dt.tzinfo is None else dt


def overdue(records, now=None):
    """Findings past their due date and not closed (criterion 10)."""
    now = now or datetime.now(timezone.utc)
    out = []
    for r in records:
        d = _parse_date(r.get("due_date"))
        if d and d < now and r.get("status") not in CLOSED_STATUSES:
            out.append(r)
    out.sort(key=lambda r: r.get("due_date") or "")
    return out


def by_status(records):
    counts = {s: 0 for s in STATUSES}
    for r in records:
        counts[r.get("status", "Open")] = counts.get(r.get("status", "Open"), 0) + 1
    return counts


def by_owner(records):
    counts = {}
    for r in records:
        if r.get("status") in CLOSED_STATUSES:
            continue
        o = r.get("owner") or "Unassigned"
        counts[o] = counts.get(o, 0) + 1
    return counts
